### ISSUE TITLE
Implement variable calculation settings option for supports

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#1072]
**Issue:** missing functionality causes serialization bug

The object, corresponding to the schema's `rigidity_group` xml element is missing. As a result, we have data loss when reading a model file that contains it.

https://github.com/strusoft/femdesign-api/blob/f93c787b85e461959642d849c451db696348bae5/FD-23.00.003-strusoft.xsd#L4171

A sample file with each support type with different rigidity settings for different calculations is attached:
[FD-all-supp-with-diff-calc-settings.zip](https://github.com/user-attachments/files/16624817/FD-all-supp-with-diff-calc-settings.zip)

![image](https://github.com/user-attachments/assets/3fdf13c4-9ca8-4a13-9c67-918663492087)

Freshdesk ticket: [43234](https://strusoft.freshdesk.com/a/tickets/43234)

**Tasks:**

- [ ] Implement `rigidity_group` in FemDesign.Core
- [ ] Update SurfaceSupport, LineSupport and PointSupport
- [ ] c# tests
- [ ] Update GH components
- [ ] GH tests
- [ ] Update documentation
- [ ] Notify the user on Freshdesk
