### ISSUE TITLE
Edge connection endpoint behaviour missing from GH

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#1104]
### Note 1: 

> 
> **This feature exists in the API**, but hasn't been implemented in the Grasshopper toolkit yet.
> 
> https://github.com/strusoft/femdesign-api/blob/82dbe19bc77b41afc932a58e7a3a2e6efdd9a375/FemDesign.Core/Shells/EdgeConnectionBase.cs#L9-L19
> 

### Note 2:

> 
> `EdgeConnection.JoinedStartPoint` and `EdgeConnection.JoinedEndPoint` properties must be `true` by default, as they are in FEM-Design.

### FEM-Design functionality:

![image](https://github.com/user-attachments/assets/61ef939a-2d68-412f-b293-e465e31d4632)

## Tasks

- [ ] Add new parameters to the existing `EdgeConnection` constructor or create a new one or add a new method to the class to set the endpoint behaviour attributes.

> 
> https://github.com/strusoft/femdesign-api/blob/82dbe19bc77b41afc932a58e7a3a2e6efdd9a375/FemDesign.Core/Shells/EdgeConnection.cs#L78-L89
> 
> `EdgeConnection.MovingLocal`, `EdgeConnection.JoinedStartPoint` and `EdgeConnection.JoinedEndPoint` should be added to the constructor as input parameters. E.g.:
> 
> ```
> private EdgeConnection(Releases.RigidityDataType3 rigidity, string libraryName = null, bool movingLocal = false, bool joinedStartPoint = true, bool joinedEndPoint = true)
>         {
>             EntityCreated();
>             MovingLocal = movingLocal;
>             JoinedStartPoint = joinedStartPoint;
>             JoinedEndPoint = joinedEndPoint;
> 
>             if (libraryName is null)
>                 this.Rigidity = rigidity;
>             else
>                 this.PredefRigidity = new Releases.RigidityDataLibType3(rigidity, libraryName);
>         }
> ```
> 

- [ ] The `MovingLocal` property controls the functionality shown in the picture below:

> ![image](https://github.com/user-attachments/assets/d14f59d3-5bd6-4d47-b825-1cfde6ed4d9c)

- [ ] Create a new "EndPointBehaviour" GH component.
- [ ] Update existing EdgeConnection GH components (`EdgeConnection.Construct`, `EdgeConnection.Hinged`, `EdgeConnection.Rigid`). Add "EndPointBehaviour" as an input parameter.
- [ ] Update `EdgeConnection.Deconstruct`

- [ ] **Notify the user!** [Discourse ticket](https://femdesign-api.discourse.group/t/edge-connection-separate-end-points-from-environment/382/3)
