### ISSUE TITLE
Add predefined line/shelledge connection types

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#365]
Allow to create and set predefined shell edge types

![image](https://user-images.githubusercontent.com/32938476/168291808-ceb6da2f-2180-4bbc-9f6d-fb451408776b.png)

![image](https://user-images.githubusercontent.com/32938476/168291742-9793273f-76bd-4079-bd55-7ba3aad283e9.png)

**Comment by xRadne** [comment]
Needed for an internal project and needs to be prioritized

**Comment by xRadne** [comment]
Using branch 364

**Comment by xRadne** [comment]
### Todo
- [ ] Rename ShellEdgeConnection => EdgeConnection
- [ ] Change Edge Connection to have property LibraryName
- [ ] Serialization to predefined if LibraryName is set
- [ ] Update Grasshopper Component

**Comment by xRadne** [comment]
![image](https://user-images.githubusercontent.com/32938476/169028010-cfc89593-4bd5-4242-8083-e9f3f8877a43.png)

**Comment by xRadne** [comment]
Merged into 21.2.0
